aws_region         = "us-east-1"
vpc_id             = "vpc-nequi-test"
subnet_ids         = ["subnet-nequi1", "subnet-nequi2"]
security_group_id  = "sg-nequi_rds"
security_group_ecs = "sg-nequi_ecs"
db_username        = "admin"
db_password        = "admin"
db_name            = "nequi"
image_tag          = "${{ secrets.ECR_REGISTRY }}/nequi-ecr:latest"