name: Deploy App

on:
  push:
    paths:
      - 'src/**'
      - 'Dockerfile'
      - '.github/workflows/deploy-app.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image
        run: |
          docker build -t nequi .
          docker tag nequi:latest ${{ secrets.ECR_REGISTRY }}/nequi-ecr:latest
          docker push ${{ secrets.ECR_REGISTRY }}/nequi-ecr:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster nequi-cluster \
            --service franchise-service \
            --force-new-deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1